language: scala
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
script:
- git config core.whitespace tab-in-indent,trailing-space,blank-at-eol && git show --oneline --check
- sbt test scripted $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_REPO_SLUG}" == "xuwei-k/sbt-global" && "${TRAVIS_BRANCH}" == "master" ]]; then echo "publish"; fi)
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
sudo: false
env:
  global:
  - secure: G9BPxSrFzvwvu82N4w1vtQtGXS5zw1KNkpkmyh7SOXChKPcgj01Ts4JLYgXSEiddjprhffJc06bmLaPP4Z9nuIjFoE5ycGgGKzE0sWFArz2S0Pc3K8yulpb/leiXMQRIeyQd/Ekc9XhrXrIc6Z7lUfh5jjyXzMLNsjqunZlUaz4n9fFLX3zGgljr/ZmCaqzb6LNSFxnJ0CMaWymodbXoCXrPZSZf8JDb0u+LfZZi4Y9dsR5LIN4PmQVBO18qO9UWiwVO3R0v8xDAImawKckj0URrh6q7BUdOKeR9F7gtk7ALW5YAdaTK43fo4Z/rM8zNRkYF+S8khJGB0waq48e8GkSRM4RpvUjr7Q/7EO/t90Je2WTV8Aja/GJpJi/nXicj7zNfHHrOktC5NPwy4BOt6Yfc+1JXiPr/3pf6wZjnYwAIASV0OYDDlQiVSo8ZPjvEfes2OLwLnIHgFsgHuPbuGv4In4Zg0u7RgWmcoY6lsQV/mRKVLeQp/6dFCWCB+lMnVvXcQFuUg29Jl25bn853CXRxdfeWSYdY8NFOYh4epCYwzOP/7KV4uo2CqOFSkptcOvADCO2NIEM86nyZclewhWUGWoJj0AlQs9YDDaXa0y5R+/8qFbsESOFEbetEuJ1UMVM0WLDMM7ZLp6k/RzHtSOkvffPRpC+M17MK2PUk5oc=
  - secure: E4Wvpi/feOv5M6npiv1rKiAZ5qCHqZ6eVDhkXAKw015R4SuU4jyn0IHzFD+kpQitoS3UPz7kO+c0HRCtipsrqw48FN9QzSUizfPKA2fXtgNR9w0e+p9SrCb2HuV/EZaQMwQlSFkMRvngyDdj6Br4XtluzI0IH0EV9IEbtqhlGo0ULQ36S9LLFS9JTT7boXIFwhCA1jDTpWxjmWV4CPYmB5WMIvawvWCUvNfDe5JbARWlOQMRBotJLALuiJT3NdolPi8dSIqDEQ41o/0NdOKxONVLtQSIajpr0VmzAw/bOotTTgcAIWDlGf4/rml8xw3h2+4sqXtTNa+bpq6OHbsPji4E09tjbujj3eFdfBXgfAn++IynbhN0/0V7OMWbKYEhZ7BOozWr1vEWPXphSBm0AI9Tsbwi0tVORRyOq0t+wyELK1TQAe/W/WjCyyPnorF4TFl69Wbb4kxZ9ZgoUaAneZA6RqeeRGXK0n0vspbqSHrfgzP7mjWnTlTr2C/69aw3+mcRT94izlTODlGcgvXDTOJd+rmWHo83zUqw6dMGLxryYp7yDorGLfu41IY/aOQYxZJ2ujsYhgxM5YF34eFXCWg9/xZYjvJ1DsTpP+NjDcT0H3AURg5UUScFh3t179LGlga+oDzujwuDLs5SaoDb7pCRViNNdcsXsKkBjWLAnYE=
addons:
  apt:
    packages:
    - oracle-java8-installer
matrix:
  include:
  - dist: trusty
    group: edge
    sudo: required
    jdk: oraclejdk9
    script:
    # https://github.com/sbt/sbt/pull/2951
    - git clone https://github.com/retronym/java9-rt-export
    - cd java9-rt-export/
    - git checkout 1019a2873d057dd7214f4135e84283695728395d
    - jdk_switcher use oraclejdk8
    - sbt package
    - jdk_switcher use oraclejdk9
    - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
    - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
    - cd ..
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/470e7ad01ee01ebb6dafa4902afe383c27222842/sbt && chmod +x sbt
    - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext test scripted
